[profile.default]
out = "out"
libs = ["lib"]
ast = true
src = "contracts"
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
# Needed for some Lido contracts that might use larger bytecode
evm_version = "paris"

# [rpc_endpoints]
# mainnet = "${ETH_RPC_URL}"
#
# # Add Etherscan API key if you want to verify contracts
# [etherscan]
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
